import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding professions...');

  const professions = [
    {
      name: 'KFZ-Mechatroniker/in',
      slug: 'kfz-mechatroniker',
      code: 'KFZ-MECH',
      category: 'Handwerk',
      subcategory: 'Fahrzeugtechnik',
      shortDescription:
        'Warte, prüfe und repariere Fahrzeuge und deren Systeme in Werkstätten und Autohäusern.',
      description:
        'Als KFZ-Mechatroniker/in diagnostizierst und behebst du Fehler an Fahrzeugen, führst Inspektionen und Wartungsarbeiten durch und rüstest Fahrzeuge mit Zusatzausstattungen aus. Du arbeitest mit modernster Diagnosetechnik und bist Experte für mechanische, elektronische und informationstechnische Systeme im Fahrzeug.',
      durationMonths: 42,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 880,
      salaryYear2: 935,
      salaryYear3: 1000,
      salaryAfter: '2.400 - 3.200 EUR',
      tags: JSON.stringify(['Auto', 'Werkstatt', 'Technik', 'Elektronik', 'Diagnose']),
      tasks: JSON.stringify([
        'Fahrzeuge warten und inspizieren',
        'Fehler diagnostizieren und beheben',
        'Bremsanlagen, Motoren und Getriebe reparieren',
        'Elektronische Systeme prüfen',
        'Abgas- und Hauptuntersuchungen vorbereiten',
      ]),
      requirements: JSON.stringify([
        'Technisches Verständnis',
        'Handwerkliches Geschick',
        'Sorgfalt und Genauigkeit',
        'Interesse an Fahrzeugtechnik',
      ]),
      skills: JSON.stringify(['Mechanik', 'Elektronik', 'Diagnosetechnik', 'Hydraulik']),
      careerPaths: JSON.stringify(['KFZ-Meister/in', 'Techniker/in', 'Serviceberater/in']),
    },
    {
      name: 'Elektroniker/in',
      slug: 'elektroniker',
      code: 'ELEK',
      category: 'Handwerk',
      subcategory: 'Elektrotechnik',
      shortDescription:
        'Installiere, warte und repariere elektrische Anlagen und Systeme in Gebäuden und Betrieben.',
      description:
        'Als Elektroniker/in planst und installierst du elektrische Anlagen, programmierst Steuerungen und sorgst für die Sicherheit elektrischer Systeme. Du arbeitest sowohl auf Baustellen als auch in Betrieben und bist Spezialist für Energie- und Gebäudetechnik.',
      durationMonths: 42,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 920,
      salaryYear2: 970,
      salaryYear3: 1060,
      salaryAfter: '2.600 - 3.500 EUR',
      tags: JSON.stringify(['Elektrik', 'Installation', 'Gebäudetechnik', 'Smart Home']),
      tasks: JSON.stringify([
        'Elektrische Anlagen planen und installieren',
        'Steuerungen und Regelungen programmieren',
        'Störungen analysieren und beheben',
        'Sicherheitsprüfungen durchführen',
        'Kunden beraten und einweisen',
      ]),
      requirements: JSON.stringify([
        'Mathematisches Verständnis',
        'Technisches Interesse',
        'Farbtüchtigkeit',
        'Sorgfältiges Arbeiten',
      ]),
      skills: JSON.stringify(['Elektrotechnik', 'Steuerungstechnik', 'Messtechnik', 'IT-Grundlagen']),
      careerPaths: JSON.stringify(['Elektromeister/in', 'Techniker/in', 'Ingenieur/in (Studium)']),
    },
    {
      name: 'Anlagenmechaniker/in für Sanitär-, Heizungs- und Klimatechnik',
      slug: 'anlagenmechaniker-shk',
      code: 'SHK',
      category: 'Handwerk',
      subcategory: 'Versorgungstechnik',
      shortDescription:
        'Installiere und warte Heizungs-, Sanitär- und Klimaanlagen in Wohn- und Gewerbegebäuden.',
      description:
        'Als Anlagenmechaniker/in SHK installierst du Heizungen, Sanitäranlagen und Klimasysteme. Du planst Rohrleitungssysteme, montierst Badezimmer und sorgst für effiziente Heizsysteme. Mit der Energiewende wird dein Beruf immer wichtiger - Wärmepumpen und Solarthermie gehören zu deinem Alltag.',
      durationMonths: 42,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 900,
      salaryYear2: 960,
      salaryYear3: 1040,
      salaryAfter: '2.500 - 3.400 EUR',
      tags: JSON.stringify(['Heizung', 'Sanitär', 'Klima', 'Wärmepumpe', 'Rohrleitungen']),
      tasks: JSON.stringify([
        'Heizungsanlagen installieren und warten',
        'Sanitäranlagen montieren',
        'Rohrleitungen verlegen und verbinden',
        'Wärmepumpen und Solaranlagen einbauen',
        'Kunden in Bedienung einweisen',
      ]),
      requirements: JSON.stringify([
        'Handwerkliches Geschick',
        'Körperliche Belastbarkeit',
        'Räumliches Vorstellungsvermögen',
        'Technisches Verständnis',
      ]),
      skills: JSON.stringify(['Rohrleitungsbau', 'Schweißtechnik', 'Wärmetechnik', 'Hydraulik']),
      careerPaths: JSON.stringify(['SHK-Meister/in', 'Techniker/in', 'Energieberater/in']),
    },
    {
      name: 'Tischler/in',
      slug: 'tischler',
      code: 'TISCH',
      category: 'Handwerk',
      subcategory: 'Holztechnik',
      shortDescription:
        'Fertige Möbel, Türen, Fenster und Innenausbauten aus Holz und Holzwerkstoffen.',
      description:
        'Als Tischler/in (auch Schreiner/in genannt) stellst du Möbel, Fenster, Türen und Treppen her. Du arbeitest sowohl mit traditionellen Handwerkzeugen als auch mit modernen CNC-Maschinen. Kreativität und Präzision zeichnen diesen Beruf aus.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 750,
      salaryYear2: 850,
      salaryYear3: 950,
      salaryAfter: '2.200 - 3.000 EUR',
      tags: JSON.stringify(['Holz', 'Möbel', 'Schreiner', 'CNC', 'Innenausbau']),
      tasks: JSON.stringify([
        'Möbel und Einrichtungen entwerfen und fertigen',
        'Holzbearbeitungsmaschinen bedienen',
        'Fenster und Türen herstellen und einbauen',
        'Oberflächen behandeln und veredeln',
        'Kundenaufträge planen und umsetzen',
      ]),
      requirements: JSON.stringify([
        'Handwerkliches Geschick',
        'Räumliches Vorstellungsvermögen',
        'Kreativität',
        'Sorgfalt',
      ]),
      skills: JSON.stringify(['Holzbearbeitung', 'CNC-Technik', 'Oberflächentechnik', 'Technisches Zeichnen']),
      careerPaths: JSON.stringify(['Tischlermeister/in', 'Gestalter/in im Handwerk', 'Restaurator/in']),
    },
    {
      name: 'Maler/in und Lackierer/in',
      slug: 'maler-und-lackierer',
      code: 'MALER',
      category: 'Handwerk',
      subcategory: 'Gestaltung',
      shortDescription:
        'Gestalte Innen- und Außenflächen mit Farben, Lacken, Tapeten und Beschichtungen.',
      description:
        'Als Maler/in und Lackierer/in gestaltest du Innenräume und Fassaden, trägst Beschichtungen auf und tapezierst Wände. Du berätst Kunden bei der Farbgestaltung und sorgst für den Schutz von Oberflächen. Kreativität und handwerkliches Können gehen hier Hand in Hand.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 770,
      salaryYear2: 850,
      salaryYear3: 980,
      salaryAfter: '2.100 - 2.800 EUR',
      tags: JSON.stringify(['Farbe', 'Gestaltung', 'Fassade', 'Tapezieren', 'Lackieren']),
      tasks: JSON.stringify([
        'Untergründe prüfen und vorbereiten',
        'Innenräume streichen und tapezieren',
        'Fassaden beschichten und gestalten',
        'Lacke und Lasuren auftragen',
        'Kunden bei Farbgestaltung beraten',
      ]),
      requirements: JSON.stringify([
        'Handwerkliches Geschick',
        'Farbgefühl',
        'Schwindelfreiheit',
        'Körperliche Fitness',
      ]),
      skills: JSON.stringify(['Beschichtungstechnik', 'Farbmischung', 'Tapezieren', 'Fassadentechnik']),
      careerPaths: JSON.stringify(['Malermeister/in', 'Gestalter/in im Handwerk', 'Restaurator/in']),
    },
    {
      name: 'Friseur/in',
      slug: 'friseur',
      code: 'FRIS',
      category: 'Handwerk',
      subcategory: 'Körperpflege',
      shortDescription:
        'Schneide, färbe und style Haare und berate Kunden zu Frisuren und Pflegeprodukten.',
      description:
        'Als Friseur/in schneidest, färbst und stylst du Haare nach den Wünschen deiner Kunden. Du berätst zu aktuellen Trends, führst Kopfhautbehandlungen durch und bist Experte für Haarpflege. Dein Arbeitsplatz ist kreativ und abwechslungsreich.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 620,
      salaryYear2: 730,
      salaryYear3: 840,
      salaryAfter: '1.800 - 2.500 EUR',
      tags: JSON.stringify(['Haare', 'Styling', 'Pflege', 'Farbe', 'Beauty']),
      tasks: JSON.stringify([
        'Haare schneiden, färben und stylen',
        'Kunden beraten und Typberatung durchführen',
        'Kopfhaut- und Haarbehandlungen durchführen',
        'Pflegeprodukte empfehlen und verkaufen',
        'Trends verfolgen und umsetzen',
      ]),
      requirements: JSON.stringify([
        'Kreativität',
        'Kommunikationsfreude',
        'Fingerfertigkeit',
        'Freundliches Auftreten',
      ]),
      skills: JSON.stringify(['Schneidetechniken', 'Färbetechniken', 'Styling', 'Beratung']),
      careerPaths: JSON.stringify(['Friseurmeister/in', 'Salonleitung', 'Maskenbildner/in']),
    },
    {
      name: 'Kaufmann/Kauffrau im Einzelhandel',
      slug: 'kaufmann-einzelhandel',
      code: 'KEH',
      category: 'Kaufmännisch',
      subcategory: 'Handel',
      shortDescription:
        'Verkaufe Waren, berate Kunden und organisiere den Geschäftsbetrieb im Einzelhandel.',
      description:
        'Als Kaufmann/Kauffrau im Einzelhandel bist du Verkaufsprofi und Organisationstalent. Du berätst Kunden, präsentierst Waren ansprechend, bearbeitest Reklamationen und kümmerst dich um Warenbestellungen und Lagerhaltung. Der Beruf bietet vielfältige Einsatzmöglichkeiten in verschiedenen Branchen.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 880,
      salaryYear2: 960,
      salaryYear3: 1090,
      salaryAfter: '2.000 - 2.800 EUR',
      tags: JSON.stringify(['Verkauf', 'Beratung', 'Handel', 'Kasse', 'Warenwirtschaft']),
      tasks: JSON.stringify([
        'Kunden beraten und Verkaufsgespräche führen',
        'Waren bestellen und annehmen',
        'Regale auffüllen und Waren präsentieren',
        'Kassiervorgänge durchführen',
        'Inventuren und Bestandskontrollen durchführen',
      ]),
      requirements: JSON.stringify([
        'Kommunikationsstärke',
        'Freundlichkeit',
        'Mathematische Grundkenntnisse',
        'Belastbarkeit',
      ]),
      skills: JSON.stringify(['Verkauf', 'Warenwirtschaft', 'Kundenservice', 'Marketing']),
      careerPaths: JSON.stringify(['Handelsfachwirt/in', 'Filialleitung', 'Selbstständigkeit']),
    },
    {
      name: 'Kaufmann/Kauffrau für Büromanagement',
      slug: 'kauffrau-bueromanagement',
      code: 'KBM',
      category: 'Kaufmännisch',
      subcategory: 'Verwaltung',
      shortDescription:
        'Organisiere Büroabläufe, bearbeite Geschäftsprozesse und kommuniziere mit Kunden und Partnern.',
      description:
        'Als Kaufmann/Kauffrau für Büromanagement organisierst du den Büroalltag, bearbeitest Aufträge und Rechnungen, koordinierst Termine und wickelst die Geschäftskorrespondenz ab. Du bist die zentrale Anlaufstelle im Unternehmen und sorgst für reibungslose Abläufe.',
      durationMonths: 36,
      schoolTypeMin: 'Realschule',
      salaryYear1: 900,
      salaryYear2: 1000,
      salaryYear3: 1100,
      salaryAfter: '2.200 - 3.000 EUR',
      tags: JSON.stringify(['Büro', 'Organisation', 'Verwaltung', 'Kommunikation', 'Buchhaltung']),
      tasks: JSON.stringify([
        'Büro- und Geschäftsprozesse organisieren',
        'Korrespondenz und E-Mails bearbeiten',
        'Aufträge und Rechnungen bearbeiten',
        'Termine koordinieren und Besprechungen vorbereiten',
        'Daten und Statistiken pflegen',
      ]),
      requirements: JSON.stringify([
        'Organisationstalent',
        'Gute Deutschkenntnisse',
        'Sorgfalt',
        'PC-Kenntnisse',
      ]),
      skills: JSON.stringify(['MS Office', 'Buchhaltung', 'Organisation', 'Kommunikation']),
      careerPaths: JSON.stringify(['Bürofachwirt/in', 'Personalfachkaufmann/-frau', 'Betriebswirt/in']),
    },
    {
      name: 'Fachinformatiker/in Anwendungsentwicklung',
      slug: 'fachinformatiker-anwendungsentwicklung',
      code: 'FIAE',
      category: 'IT',
      subcategory: 'Softwareentwicklung',
      shortDescription:
        'Entwickle Software, programmiere Anwendungen und gestalte digitale Lösungen für Unternehmen.',
      description:
        'Als Fachinformatiker/in für Anwendungsentwicklung entwirfst, programmierst und testest du Softwarelösungen. Du analysierst Kundenanforderungen, entwickelst maßgeschneiderte Programme und sorgst für deren Dokumentation und Wartung. Der Beruf ist ideal für alle, die gerne logisch denken und kreativ coden.',
      durationMonths: 36,
      schoolTypeMin: 'Realschule',
      salaryYear1: 1050,
      salaryYear2: 1100,
      salaryYear3: 1200,
      salaryAfter: '3.000 - 4.500 EUR',
      tags: JSON.stringify(['Programmierung', 'Software', 'Code', 'Web', 'App']),
      tasks: JSON.stringify([
        'Software konzipieren und entwickeln',
        'Benutzeroberflächen gestalten',
        'Datenbanken entwerfen und verwalten',
        'Anwendungen testen und Fehler beheben',
        'Technische Dokumentation erstellen',
      ]),
      requirements: JSON.stringify([
        'Logisches Denkvermögen',
        'Mathematisches Verständnis',
        'Englischkenntnisse',
        'Teamfähigkeit',
      ]),
      skills: JSON.stringify(['Programmiersprachen', 'Datenbanken', 'Webentwicklung', 'Softwaredesign']),
      careerPaths: JSON.stringify(['Senior Developer', 'IT-Projektleiter/in', 'Informatikstudium']),
    },
    {
      name: 'Fachinformatiker/in Systemintegration',
      slug: 'fachinformatiker-systemintegration',
      code: 'FISI',
      category: 'IT',
      subcategory: 'Netzwerktechnik',
      shortDescription:
        'Plane, installiere und betreue IT-Systeme, Netzwerke und Infrastrukturen in Unternehmen.',
      description:
        'Als Fachinformatiker/in für Systemintegration richtest du IT-Systeme ein, vernetzt Hard- und Softwarekomponenten und betreust Netzwerke. Du bist der Ansprechpartner bei technischen Problemen und sorgst für sichere, stabile IT-Infrastrukturen. Cloud-Technologien und IT-Sicherheit gehören zu deinem Alltag.',
      durationMonths: 36,
      schoolTypeMin: 'Realschule',
      salaryYear1: 1050,
      salaryYear2: 1100,
      salaryYear3: 1200,
      salaryAfter: '2.800 - 4.000 EUR',
      tags: JSON.stringify(['Netzwerk', 'Server', 'IT-Support', 'Cloud', 'Security']),
      tasks: JSON.stringify([
        'IT-Systeme installieren und konfigurieren',
        'Netzwerke planen und einrichten',
        'Störungen analysieren und beseitigen',
        'IT-Sicherheitsmaßnahmen umsetzen',
        'Benutzer schulen und unterstützen',
      ]),
      requirements: JSON.stringify([
        'Technisches Verständnis',
        'Analytisches Denken',
        'Englischkenntnisse',
        'Kommunikationsstärke',
      ]),
      skills: JSON.stringify(['Netzwerktechnik', 'Betriebssysteme', 'IT-Sicherheit', 'Cloud Computing']),
      careerPaths: JSON.stringify(['IT-Administrator/in', 'Netzwerkarchitekt/in', 'IT-Berater/in']),
    },
    {
      name: 'Koch/Köchin',
      slug: 'koch',
      code: 'KOCH',
      category: 'Gastronomie',
      subcategory: 'Küche',
      shortDescription:
        'Bereite Speisen zu, erstelle Menüpläne und organisiere die Küche in Restaurants und Hotels.',
      description:
        'Als Koch/Köchin bereitest du Speisen aller Art zu, erstellst Speisepläne, kalkulierst Rezepte und sorgst für Hygiene in der Küche. Du arbeitest in Restaurants, Hotels, Kantinen oder Catering-Unternehmen. Kreativität, Belastbarkeit und ein guter Geschmackssinn sind dein Handwerkszeug.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 800,
      salaryYear2: 900,
      salaryYear3: 1000,
      salaryAfter: '2.000 - 2.800 EUR',
      tags: JSON.stringify(['Küche', 'Kochen', 'Restaurant', 'Speisen', 'Gastronomie']),
      tasks: JSON.stringify([
        'Speisen nach Rezepten und eigenen Ideen zubereiten',
        'Menüs und Speisekarten planen',
        'Lebensmittel einkaufen und lagern',
        'Hygienevorschriften einhalten (HACCP)',
        'Kosten kalkulieren und Portionen berechnen',
      ]),
      requirements: JSON.stringify([
        'Kreativität',
        'Belastbarkeit',
        'Teamfähigkeit',
        'Guter Geschmacks- und Geruchssinn',
      ]),
      skills: JSON.stringify(['Kochtechniken', 'Lebensmittelkunde', 'Hygiene', 'Kalkulation']),
      careerPaths: JSON.stringify(['Küchenmeister/in', 'Küchenchef/in', 'Eigenes Restaurant']),
    },
    {
      name: 'Fachkraft für Lagerlogistik',
      slug: 'fachkraft-lagerlogistik',
      code: 'LAGER',
      category: 'Kaufmännisch',
      subcategory: 'Logistik',
      shortDescription:
        'Organisiere Warenflüsse, verwalte Lagerbestände und koordiniere den Versand von Gütern.',
      description:
        'Als Fachkraft für Lagerlogistik nimmst du Waren an, prüfst Lieferungen, lagerst Güter fachgerecht ein und stellst Sendungen zusammen. Du bedienst Gabelstapler, nutzt Lagerverwaltungssysteme und optimierst logistische Prozesse. Ein Beruf mit Zukunft in der vernetzten Wirtschaft.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 870,
      salaryYear2: 940,
      salaryYear3: 1020,
      salaryAfter: '2.200 - 2.900 EUR',
      tags: JSON.stringify(['Lager', 'Logistik', 'Versand', 'Gabelstapler', 'Warenwirtschaft']),
      tasks: JSON.stringify([
        'Waren annehmen und kontrollieren',
        'Güter fachgerecht einlagern',
        'Kommissionierungen durchführen',
        'Versand vorbereiten und organisieren',
        'Lagerbestände verwalten und optimieren',
      ]),
      requirements: JSON.stringify([
        'Organisationstalent',
        'Körperliche Fitness',
        'Sorgfalt',
        'Teamfähigkeit',
      ]),
      skills: JSON.stringify(['Lagerverwaltung', 'Gabelstaplerführung', 'EDV-Kenntnisse', 'Logistikplanung']),
      careerPaths: JSON.stringify(['Logistikmeister/in', 'Fachwirt/in für Logistik', 'Disponent/in']),
    },
    {
      name: 'Medizinische/r Fachangestellte/r',
      slug: 'medizinische-fachangestellte',
      code: 'MFA',
      category: 'Gesundheit',
      subcategory: 'Medizin',
      shortDescription:
        'Assistiere Ärzten, betreue Patienten und organisiere den Praxisablauf in Arztpraxen.',
      description:
        'Als Medizinische/r Fachangestellte/r assistierst du bei Untersuchungen und Behandlungen, nimmst Blut ab, legst Verbände an und organisierst den gesamten Praxisablauf. Du bist die erste Anlaufstelle für Patienten und sorgst für einen reibungslosen Tagesablauf in der Arztpraxis.',
      durationMonths: 36,
      schoolTypeMin: 'Realschule',
      salaryYear1: 920,
      salaryYear2: 980,
      salaryYear3: 1060,
      salaryAfter: '2.200 - 3.000 EUR',
      tags: JSON.stringify(['Medizin', 'Arztpraxis', 'Patienten', 'Gesundheit', 'Labor']),
      tasks: JSON.stringify([
        'Patienten empfangen und betreuen',
        'Bei Untersuchungen und Behandlungen assistieren',
        'Blutabnahme und Injektionen durchführen',
        'Termine verwalten und Abrechnungen erstellen',
        'Hygienemaßnahmen einhalten und dokumentieren',
      ]),
      requirements: JSON.stringify([
        'Einfühlungsvermögen',
        'Sorgfalt',
        'Verschwiegenheit',
        'Keine Angst vor Blut',
      ]),
      skills: JSON.stringify(['Medizinische Assistenz', 'Praxisorganisation', 'Abrechnung', 'Hygiene']),
      careerPaths: JSON.stringify(['Praxismanager/in', 'Fachwirt/in im Gesundheitswesen', 'Studium Medizin/Pflege']),
    },
    {
      name: 'Industriemechaniker/in',
      slug: 'industriemechaniker',
      code: 'INDM',
      category: 'Handwerk',
      subcategory: 'Metalltechnik',
      shortDescription:
        'Stelle Bauteile her, montiere Maschinen und sorge für deren Instandhaltung in der Industrie.',
      description:
        'Als Industriemechaniker/in stellst du Geräteteile und Baugruppen für Maschinen und Produktionsanlagen her, richtest diese ein und hältst sie instand. Du arbeitest mit Metall, programmierst CNC-Maschinen und sorgst dafür, dass die Produktion reibungslos läuft. Ein vielseitiger Beruf in der Industrie.',
      durationMonths: 42,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 980,
      salaryYear2: 1050,
      salaryYear3: 1140,
      salaryAfter: '2.800 - 3.500 EUR',
      tags: JSON.stringify(['Metall', 'Maschinen', 'Industrie', 'CNC', 'Instandhaltung']),
      tasks: JSON.stringify([
        'Bauteile aus Metall herstellen und bearbeiten',
        'Maschinen und Anlagen montieren',
        'CNC-Maschinen programmieren und bedienen',
        'Störungen diagnostizieren und beseitigen',
        'Wartungs- und Inspektionsarbeiten durchführen',
      ]),
      requirements: JSON.stringify([
        'Technisches Verständnis',
        'Handwerkliches Geschick',
        'Räumliches Vorstellungsvermögen',
        'Mathematische Kenntnisse',
      ]),
      skills: JSON.stringify(['Metallbearbeitung', 'CNC-Technik', 'Pneumatik', 'Steuerungstechnik']),
      careerPaths: JSON.stringify(['Industriemeister/in', 'Techniker/in', 'Ingenieur/in (Studium)']),
    },
    {
      name: 'Zimmerer/Zimmerin',
      slug: 'zimmerer',
      code: 'ZIMM',
      category: 'Bau',
      subcategory: 'Holzbau',
      shortDescription:
        'Errichte Holzkonstruktionen, Dachstühle und Fachwerke auf Baustellen und in Werkstätten.',
      description:
        'Als Zimmerer/Zimmerin errichtest du Holzkonstruktionen wie Dachstühle, Holzrahmenwände und Fachwerke. Du arbeitest sowohl in der Werkstatt als auch auf Baustellen und verbindest traditionelles Handwerk mit moderner Technik. Holzbau ist nachhaltig und zukunftsorientiert.',
      durationMonths: 36,
      schoolTypeMin: 'Hauptschule',
      salaryYear1: 850,
      salaryYear2: 1050,
      salaryYear3: 1260,
      salaryAfter: '2.600 - 3.400 EUR',
      tags: JSON.stringify(['Holzbau', 'Dachstuhl', 'Baustelle', 'Fachwerk', 'Nachhaltigkeit']),
      tasks: JSON.stringify([
        'Dachstühle und Holzkonstruktionen errichten',
        'Holzrahmenwände und Decken bauen',
        'Holz zuschneiden und Verbindungen herstellen',
        'Bauzeichnungen lesen und umsetzen',
        'Altbausanierungen durchführen',
      ]),
      requirements: JSON.stringify([
        'Körperliche Fitness',
        'Schwindelfreiheit',
        'Handwerkliches Geschick',
        'Teamfähigkeit',
      ]),
      skills: JSON.stringify(['Holzbau', 'Abbund', 'Baustatik', 'Dachtechnik']),
      careerPaths: JSON.stringify(['Zimmermeister/in', 'Restaurator/in', 'Bauingenieur/in (Studium)']),
    },
  ];

  for (const profession of professions) {
    await prisma.profession.upsert({
      where: { slug: profession.slug },
      update: {
        name: profession.name,
        code: profession.code,
        category: profession.category,
        subcategory: profession.subcategory,
        shortDescription: profession.shortDescription,
        description: profession.description,
        durationMonths: profession.durationMonths,
        schoolTypeMin: profession.schoolTypeMin,
        salaryYear1: profession.salaryYear1,
        salaryYear2: profession.salaryYear2,
        salaryYear3: profession.salaryYear3,
        salaryAfter: profession.salaryAfter,
        tags: profession.tags,
        tasks: profession.tasks,
        requirements: profession.requirements,
        skills: profession.skills,
        careerPaths: profession.careerPaths,
        isActive: true,
      },
      create: profession,
    });

    console.log(`  Seeded: ${profession.name}`);
  }

  console.log(`\nDone! Seeded ${professions.length} professions.`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
